version: '2'

services:

    elasticsearch:
        image: elasticsearch
        volumes:
            - elasticdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
    
    kibana:
        image: kibana
        links:
            - elasticsearch:elasticsearch
        ports:
            - "5601:5601"

volumes:
    elasticdata:
        driver: "local"
